#!/bin/sh

echo "-- create log dir for btcagent (multi user version)"
mkdir /var/log/btcagent-mu

echo "-- set minfds=65535 in supervisor.conf"
cat /etc/supervisor/supervisord.conf | grep -v 'minfds\s*=' | sed '/\[supervisord\]/a\minfds=65535' | tee /etc/supervisor/supervisord.conf | grep 'minfds\s*='

echo "-- start supervisor & running btcagent (multi user version)"
service supervisor start
echo "-- start btcagent (multi user version)"
supervisorctl reread
supervisorctl update
supervisorctl status btcagent-mu

echo "-- Install successfully."
echo # empty line
echo "-- Usage:"
echo "* Edit config file:"
echo "    vim /etc/btcagent-mu/agent_conf.json"
echo "* Start supervisor (daemon service of btcagent)"
echo "    service start supervisor"
echo "* Restart btcagent (multi user version):"
echo "    supervisorctl restart btcagent-mu"
echo "* Stop btcagent (multi user version):"
echo "    supervisorctl stop btcagent-mu"
echo "* Show logs:"
echo "    tail -F /var/log/btcagent-mu/*INFO"
echo "* Count connections:"
echo "    netstat -antp | grep btcagent-mu"
